#!/bin/bash

# 打包發布版本腳本
# 生成 Android App Bundle (AAB) 用於上傳到 Google Play

set -e

echo "=========================================="
echo "打包 Android 發布版本"
echo "=========================================="
echo ""

# 檢查是否在正確的目錄
if [ ! -f "package.json" ]; then
    echo "錯誤：請在專案根目錄執行此腳本"
    exit 1
fi

# 自動檢測並設置 Java 環境
find_java() {
    # 檢查 Android Studio 的 JDK
    if [ -d "/Applications/Android Studio.app/Contents/jbr/Contents/Home" ]; then
        export JAVA_HOME="/Applications/Android Studio.app/Contents/jbr/Contents/Home"
        export PATH="$JAVA_HOME/bin:$PATH"
        echo "使用 Android Studio 的 JDK: $JAVA_HOME"
        return 0
    fi
    
    # 檢查系統 Java
    if command -v java &> /dev/null && java -version &> /dev/null 2>&1; then
        JAVA_HOME=$(/usr/libexec/java_home 2>/dev/null || echo "")
        if [ -n "$JAVA_HOME" ]; then
            export JAVA_HOME
            export PATH="$JAVA_HOME/bin:$PATH"
            echo "使用系統 Java: $JAVA_HOME"
            return 0
        fi
    fi
    
    return 1
}

# 設置 Java 環境
if ! find_java; then
    echo "警告：無法自動檢測 Java，嘗試使用 local.properties 配置"
fi

# 確保 local.properties 存在
if [ ! -f "android/local.properties" ]; then
    echo "創建 android/local.properties..."
    cat > android/local.properties << EOF
## This file is automatically generated.
sdk.dir=\$HOME/Library/Android/sdk
EOF
fi

# 檢查 keystore.properties 是否存在
if [ ! -f "android/keystore.properties" ]; then
    echo "錯誤：找不到 android/keystore.properties"
    echo ""
    echo "請先："
    echo "1. 執行 android/generate-keystore.sh 生成密鑰庫"
    echo "2. 複製 android/keystore.properties.example 為 android/keystore.properties"
    echo "3. 填入您的密鑰庫資訊"
    exit 1
fi

echo "步驟 1/4: 清理舊的構建文件..."
cd android
./gradlew clean
cd ..

echo ""
echo "步驟 2/4: 安裝依賴..."
npm install

echo ""
echo "步驟 3/4: 生成發布版本 AAB..."
cd android
./gradlew bundleRelease
cd ..

echo ""
echo "步驟 4/4: 檢查生成的文件..."

AAB_PATH="android/app/build/outputs/bundle/release/app-release.aab"

if [ -f "$AAB_PATH" ]; then
    AAB_SIZE=$(du -h "$AAB_PATH" | cut -f1)
    echo ""
    echo "✓ 打包成功！"
    echo ""
    echo "AAB 文件位置: $AAB_PATH"
    echo "文件大小: $AAB_SIZE"
    echo ""
    echo "下一步："
    echo "1. 登入 Google Play Console (https://play.google.com/console)"
    echo "2. 選擇您的應用程式或創建新應用"
    echo "3. 進入「發布」>「生產環境」"
    echo "4. 上傳此 AAB 文件"
    echo ""
else
    echo ""
    echo "✗ 打包失敗！找不到 AAB 文件"
    exit 1
fi

